### ISSUE TITLE
Where is  "It also creates/appends data to  2 all_* files in the present folder that increase in size every time you run the script" coded?

### ISSUE THREAD

**Issue by daaronr** [TWJolly/fundraising_data_pull#14]

**Comment by TWJolly** [comment]
I think that's outdated - was unnecessary - we should update the Read-Me

**Comment by daaronr** [comment]
So, we no longer want to create the 'all' file I guess? I suppose it shouldn't be needed in the process of the experiment if we do the seeds every time we do a download. However, if we cannot assure that we do this (e.g., what if we accidentally run it an extra time), we need to be sure we have the list of *all new pages* that need seeding. Am I misunderstanding?

**Comment by TWJolly** [comment]
Yes, that should be what it's doing now!
