### ISSUE TITLE
Correct mappings to all charities? (does the app also search by regno or justgiving_id and where do these come from?) 

### ISSUE THREAD

**Issue by daaronr** [TWJolly/fundraising_data_pull#7]
I'm trying to run the app with some new charities (effective_charities_plus.csv) but it doesn't seem to be picking up everything. E.g., "Medecins Sans   Frontieres (UK)"... because of unicode/accents. Can/does the app also search by regno or justgiving_id for the charity? Also, where did we get "justgiving_id"  from?

**Comment by daaronr** [comment]
I see the app drops the charity from charity_data if we don't have a value here.  There seems to be a workaround way to look these up at https://developer.justgiving.com/apidocs/sdi#, look in the link... but this works only imperfectly

**Comment by daaronr** [comment]
Typing in "Medecins Sans Frontieres (UK)" (without accents) seems to have worked ... at least it recovered 20 fundraisers

**Comment by TWJolly** [comment]
Had to go back to older version of master to merge my earlier commits. Could you branch the current version of master and make these (https://github.com/TWJolly/fundraising_data_pull/commit/0fe803342d5217d3cda36f23d8705f5fd16cc910) changes again? - only try and merge into master when it's definitely working!

**Comment by daaronr** [comment]
OK. I am trying out your committed version. Next I will try re-including my changes (https://github.com/TWJolly/fundraising_data_pull/commit/0fe803342d5217d3cda36f23d8705f5fd16cc910) one by one and make sure it still runs ... then merge them in. Some things we may need to discuss, however, like how to use the correct charity ID.
